### ISSUE TITLE
Remove Assets from Source Repository

### ISSUE THREAD

**Issue by OpenTournament** [OpenTournament/OpenTournament#31] opened 2020-06-16 06:16 UTC
- [ ] SciFiWeaponsDark
- [x] Old Map Shells
- [ ] 100 MB+ Asset Files

**Comment by Saibamen** [comment] 2020-06-17 18:32
Duplicate of https://github.com/OpenTournament/OpenTournament/issues/30...

**Comment by vladserbanescu11** [comment] 2020-08-04 22:09
Closing duplicated issue which is also solved and no longer relevant.

**Closed by vladserbanescu11** 2020-08-04 22:09 UTC
